# Generated by Django 5.0.4 on 2024-05-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, help_text="Vaqt limiti minutlarda bo'lishi kerak ", null=True),
        ),
    ]
