# Generated by Django 5.0.4 on 2024-05-04 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_exam_end_date_alter_exam_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='correct_option',
            field=models.CharField(help_text="To'g'ri javob ,bu yerga to'ti javob tozilgan variant tartib raqamini yozing  ( masalan ,1 yoki 2 yoki 3 .)", max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='exam.exam'),
        ),
    ]
