# Generated by Django 5.0.4 on 2024-05-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='is_teacher',
            new_name='are_you_teacher',
        ),
    ]
